/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lameza;

import Controller_Connector.DBConnect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class AdminTabForm extends javax.swing.JFrame {
    private Connection con;

    public AdminTabForm() {
           initComponents();
    DBConnect.getDBConnection(); // Ensure DB connection is initialized
    con = DBConnect.getConnection(); // Retrieve the connection
    if (con == null) {
        JOptionPane.showMessageDialog(this, "Database connection failed. Check DB settings.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
}
private void loadReservationData() {
    DefaultTableModel model = (DefaultTableModel) reservationtable.getModel();
    model.setRowCount(0); // Clear existing rows before loading new data

    try {
        String query = "SELECT * FROM lameza_reservation"; // Replace with your table name
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Populate the table row by row
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("reservationID"),
                rs.getString("name"),
                rs.getString("contact"),
                rs.getString("email"),
                rs.getInt("num_of_seats"),
                rs.getDate("date").toString(), // Convert Date to String
                rs.getString("time"),
                rs.getInt("num_table")
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading reservations: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
 private void updateReservation(int reservationID, String name, String contact, String email, int numSeats, String date, String time, int numTable) {
    String query = "UPDATE lameza_reservation SET "
            + "name = ?, contact = ?, email = ?, num_of_seats = ?, date = ?, time = ?, num_table = ? "
            + "WHERE reservationID = ?";

    try (PreparedStatement pst = con.prepareStatement(query)) {
        // Set the query parameters
        pst.setString(1, name);
        pst.setString(2, contact);
        pst.setString(3, email);
        pst.setInt(4, numSeats);
        pst.setString(5, date);
        pst.setString(6, time);
        pst.setInt(7, numTable);
        pst.setInt(8, reservationID);

        // Execute the update
        int rowsUpdated = pst.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Reservation updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadReservationData(); // Reload table data to show the updates
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update reservation.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error updating reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
} 
private void deleteReservation(int reservationID) {
    String query = "DELETE FROM lameza_reservation WHERE reservationID = ?";
    
    try (PreparedStatement pst = con.prepareStatement(query)) {
        // Set the query parameter
        pst.setInt(1, reservationID);

        // Execute the delete operation
        int rowsDeleted = pst.executeUpdate();
        if (rowsDeleted > 0) {
            JOptionPane.showMessageDialog(this, "Reservation deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadReservationData(); // Reload table data to reflect the deletion
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete reservation.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel331 = new javax.swing.JPanel();
        jLabel313 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addTab("tab3", jPanel14);

        jPanel1.setBackground(new java.awt.Color(231, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 51, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(231, 213, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservationtable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ReservationID", "Name", "ContactNumber", "Email", "NumberOfSeat", "Date", "Time", "Table"
            }
        ));
        jScrollPane1.setViewportView(reservationtable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 840));

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 810, -1, -1));

        jScrollPane2.setViewportView(jPanel2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 880, 510));

        jButton1.setBackground(new java.awt.Color(231, 213, 195));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("VIEW");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 180, 40));

        jButton2.setBackground(new java.awt.Color(231, 213, 195));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 51, 0));
        jButton2.setText("UPDATE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 180, 40));

        jButton9.setBackground(new java.awt.Color(231, 213, 195));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 51, 0));
        jButton9.setText("CREATE");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 180, 40));

        jButton10.setBackground(new java.awt.Color(231, 213, 195));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 51, 0));
        jButton10.setText("DELETE");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 180, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 920, 640));

        jPanel331.setBackground(new java.awt.Color(102, 51, 0));
        jPanel331.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel313.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel313.setForeground(new java.awt.Color(231, 213, 195));
        jLabel313.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel313.setText("LAMÈZA  ");
        jPanel331.add(jLabel313, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 60));

        jPanel1.add(jPanel331, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1460, 70));

        jPanel76.setBackground(new java.awt.Color(102, 51, 0));
        jPanel76.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel76.setForeground(new java.awt.Color(102, 51, 0));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel77.setBackground(new java.awt.Color(231, 213, 195));
        jPanel77.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel77.setForeground(new java.awt.Color(102, 51, 0));
        jPanel77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel78.setBackground(new java.awt.Color(102, 51, 0));
        jPanel78.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel77.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 160));

        jButton25.setBackground(new java.awt.Color(64, 32, 1));
        jButton25.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton25.setForeground(new java.awt.Color(231, 213, 195));
        jButton25.setText("jButton9");
        jButton25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton25.setFocusPainted(false);
        jPanel77.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 40));

        jButton26.setBackground(new java.awt.Color(64, 32, 1));
        jButton26.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton26.setForeground(new java.awt.Color(231, 213, 195));
        jButton26.setText("jButton9");
        jButton26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton26.setFocusPainted(false);
        jPanel77.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 40));

        jButton27.setBackground(new java.awt.Color(64, 32, 1));
        jButton27.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton27.setForeground(new java.awt.Color(231, 213, 195));
        jButton27.setText("jButton9");
        jButton27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton27.setFocusPainted(false);
        jPanel77.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 40));

        jButton28.setBackground(new java.awt.Color(64, 32, 1));
        jButton28.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton28.setForeground(new java.awt.Color(231, 213, 195));
        jButton28.setText("RESERVATIONS");
        jButton28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton28.setFocusPainted(false);
        jPanel77.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 40));

        jButton29.setBackground(new java.awt.Color(64, 32, 1));
        jButton29.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton29.setForeground(new java.awt.Color(231, 213, 195));
        jButton29.setText("jButton9");
        jButton29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton29.setFocusPainted(false);
        jPanel77.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 40));

        jPanel76.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 250, 660));

        jPanel1.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 750));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homepage (5).jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1460, 810));

        jTabbedPane1.addTab("RESERVATION", jPanel1);

        jPanel13.setBackground(new java.awt.Color(231, 213, 195));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(102, 51, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(231, 213, 195));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("LAMÈZA  ");
        jPanel15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel13.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1470, 90));

        jPanel24.setBackground(new java.awt.Color(102, 51, 0));
        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel24.setForeground(new java.awt.Color(102, 51, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(231, 213, 195));
        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.setForeground(new java.awt.Color(102, 51, 0));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(102, 51, 0));
        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 160));

        jButton11.setBackground(new java.awt.Color(64, 32, 1));
        jButton11.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(231, 213, 195));
        jButton11.setText("jButton9");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setFocusPainted(false);
        jPanel25.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 210, 40));

        jButton12.setBackground(new java.awt.Color(64, 32, 1));
        jButton12.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(231, 213, 195));
        jButton12.setText("jButton9");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setFocusPainted(false);
        jPanel25.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 40));

        jButton13.setBackground(new java.awt.Color(64, 32, 1));
        jButton13.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(231, 213, 195));
        jButton13.setText("jButton9");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.setFocusPainted(false);
        jPanel25.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 40));

        jButton14.setBackground(new java.awt.Color(64, 32, 1));
        jButton14.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(231, 213, 195));
        jButton14.setText("RESERVATIONS");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.setFocusPainted(false);
        jPanel25.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 40));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 700));

        jPanel13.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 290, 740));

        jTabbedPane1.addTab("tab2", jPanel13);

        jPanel5.setBackground(new java.awt.Color(231, 213, 195));
        jTabbedPane1.addTab("tab4", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       loadReservationData();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
      // TODO add your handling code here:
         // TODO add your handling code here:
        int selectedRow = reservationtable.getSelectedRow(); // Get selected row index
    
    if (selectedRow != -1) { // Ensure a row is selected
        // Retrieve current data from the selected row
        int reservationID = (int) reservationtable.getValueAt(selectedRow, 0);
        String[] fields = {"Name", "Contact", "Email", "Number of Seats", "Date", "Time", "Table"};
        String[] currentValues = {
            (String) reservationtable.getValueAt(selectedRow, 1),
            (String) reservationtable.getValueAt(selectedRow, 2),
            (String) reservationtable.getValueAt(selectedRow, 3),
            reservationtable.getValueAt(selectedRow, 4).toString(),
            (String) reservationtable.getValueAt(selectedRow, 5),
            (String) reservationtable.getValueAt(selectedRow, 6),
            reservationtable.getValueAt(selectedRow, 7).toString()
        };
        
        // Let user choose which field to update
        String selectedField = (String) JOptionPane.showInputDialog(
            this,
            "Select the field to update:",
            "Update Field",
            JOptionPane.QUESTION_MESSAGE,
            null,
            fields,
            fields[0]
        );
        
        if (selectedField != null) { // User did not cancel
            int fieldIndex = java.util.Arrays.asList(fields).indexOf(selectedField);
            String newValue = JOptionPane.showInputDialog(this, "Enter new value for " + selectedField, currentValues[fieldIndex]);
            
            if (newValue != null && !newValue.trim().isEmpty()) { // User provided a valid input
                // Update only the selected field
                try {
                    String updateQuery = "UPDATE lameza_reservation SET " + getColumnName(selectedField) + " = ? WHERE reservationID = ?";
                    try (PreparedStatement pst = con.prepareStatement(updateQuery)) {
                        // Set parameters based on selected field
                        if (fieldIndex == 3 || fieldIndex == 6) { // For int fields: Number of Seats or Table
                            pst.setInt(1, Integer.parseInt(newValue));
                        } else {
                            pst.setString(1, newValue); // For other fields
                        }
                        pst.setInt(2, reservationID); // Set reservationID
                        
                        int rowsUpdated = pst.executeUpdate();
                        if (rowsUpdated > 0) {
                            JOptionPane.showMessageDialog(this, "Reservation updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                            loadReservationData(); // Reload table data to show the updates
                        } else {
                            JOptionPane.showMessageDialog(this, "Failed to update reservation.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error updating reservation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(this, "Invalid input for " + selectedField + ". Please enter a valid value.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Update cancelled or invalid input.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a reservation to update.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

// Helper method to map field names to column names in the database
private String getColumnName(String field) {
    switch (field) {
        case "Name":
            return "name";
        case "Contact":
            return "contact";
        case "Email":
            return "email";
        case "Number of Seats":
            return "num_of_seats";
        case "Date":
            return "date";
        case "Time":
            return "time";
        case "Table":
            return "num_table";
        default:
            throw new IllegalArgumentException("Unknown field: " + field);
    }


        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ReservationRequestForm rrf = new ReservationRequestForm();
        rrf.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int selectedRow = reservationtable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a reservation to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Confirm deletion
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this reservation?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return; // Cancel the deletion if the user chooses "No"
    }

    // Retrieve reservationID from the selected row
    int reservationID = (int) reservationtable.getValueAt(selectedRow, 0); // Assuming the first column contains reservationID

    // Call deleteReservation method
    deleteReservation(reservationID);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTabForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel331;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable reservationtable;
    // End of variables declaration//GEN-END:variables
}
