/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lameza;

/**
 *
 * @author Kyla Alvarez
 */
public class CustomerTabForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerTabForm
     */
    public CustomerTabForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane15 = new javax.swing.JScrollPane();
        jPanel232 = new javax.swing.JPanel();
        jLabel225 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel233 = new javax.swing.JPanel();
        jButton46 = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jPanel234 = new javax.swing.JPanel();
        jButton47 = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jPanel235 = new javax.swing.JPanel();
        jButton48 = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel236 = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        jPanel237 = new javax.swing.JPanel();
        jButton50 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jPanel238 = new javax.swing.JPanel();
        jButton51 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel331 = new javax.swing.JPanel();
        jLabel313 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel232.setBackground(new java.awt.Color(102, 51, 0));
        jPanel232.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel232.add(jLabel225, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel31.setBackground(new java.awt.Color(231, 213, 195));
        jPanel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel233.setBackground(new java.awt.Color(255, 255, 255));
        jPanel233.setLayout(new java.awt.BorderLayout());

        jButton46.setBackground(new java.awt.Color(102, 51, 0));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton46.setForeground(new java.awt.Color(231, 213, 195));
        jButton46.setText("AMUSE-BOUCHE");
        jButton46.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel233.add(jButton46, java.awt.BorderLayout.PAGE_START);

        jPanel31.add(jPanel233, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 170));

        jPanel32.setBackground(new java.awt.Color(231, 213, 195));
        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel234.setBackground(new java.awt.Color(255, 255, 255));
        jPanel234.setLayout(new java.awt.BorderLayout());

        jButton47.setBackground(new java.awt.Color(102, 51, 0));
        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton47.setForeground(new java.awt.Color(231, 213, 195));
        jButton47.setText("APPETIZER");
        jButton47.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel234.add(jButton47, java.awt.BorderLayout.PAGE_START);

        jPanel32.add(jPanel234, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 170));

        jPanel33.setBackground(new java.awt.Color(231, 213, 195));
        jPanel33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel235.setBackground(new java.awt.Color(255, 255, 255));
        jPanel235.setLayout(new java.awt.BorderLayout());

        jButton48.setBackground(new java.awt.Color(102, 51, 0));
        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton48.setForeground(new java.awt.Color(231, 213, 195));
        jButton48.setText("SOUPS AND SALADS");
        jButton48.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel235.add(jButton48, java.awt.BorderLayout.PAGE_START);

        jPanel33.add(jPanel235, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 270, 170));

        jPanel34.setBackground(new java.awt.Color(231, 213, 195));
        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel236.setBackground(new java.awt.Color(255, 255, 255));
        jPanel236.setLayout(new java.awt.BorderLayout());

        jButton49.setBackground(new java.awt.Color(102, 51, 0));
        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton49.setForeground(new java.awt.Color(231, 213, 195));
        jButton49.setText("MAIN COURSES");
        jButton49.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel236.add(jButton49, java.awt.BorderLayout.PAGE_START);

        jPanel34.add(jPanel236, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 270, 170));

        jPanel35.setBackground(new java.awt.Color(231, 213, 195));
        jPanel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel237.setBackground(new java.awt.Color(255, 255, 255));
        jPanel237.setLayout(new java.awt.BorderLayout());

        jButton50.setBackground(new java.awt.Color(102, 51, 0));
        jButton50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton50.setForeground(new java.awt.Color(231, 213, 195));
        jButton50.setText("DESSERTS");
        jButton50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel237.add(jButton50, java.awt.BorderLayout.PAGE_START);

        jPanel35.add(jPanel237, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 270, 170));

        jPanel36.setBackground(new java.awt.Color(231, 213, 195));
        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel238.setBackground(new java.awt.Color(255, 255, 255));
        jPanel238.setLayout(new java.awt.BorderLayout());

        jButton51.setBackground(new java.awt.Color(102, 51, 0));
        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton51.setForeground(new java.awt.Color(231, 213, 195));
        jButton51.setText("BEVERAGES");
        jButton51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel238.add(jButton51, java.awt.BorderLayout.PAGE_START);

        jPanel36.add(jPanel238, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 150));

        jPanel232.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, 270, 170));

        jLabel6.setText("jLabel1");
        jPanel232.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1220, -1, -1));

        jScrollPane15.setViewportView(jPanel232);

        getContentPane().add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 820));

        jPanel23.setBackground(new java.awt.Color(231, 213, 195));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel331.setBackground(new java.awt.Color(102, 51, 0));
        jPanel331.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel313.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel313.setForeground(new java.awt.Color(231, 213, 195));
        jLabel313.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel313.setText("LAMÈZA  ");
        jPanel331.add(jLabel313, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 60));

        jPanel23.add(jPanel331, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1140, 70));

        jPanel24.setBackground(new java.awt.Color(102, 51, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 213, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(231, 213, 195));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/roll_1.jpg"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 213, 195));
        jLabel2.setText("Quantity:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 30));

        jLabel3.setBackground(new java.awt.Color(231, 213, 195));
        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 213, 195));
        jLabel3.setText("Buttered brioche with tarragon mayo.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 213, 195));
        jLabel4.setText("Mini Lobster Roll ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jSpinner1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 130, -1));

        jButton1.setBackground(new java.awt.Color(231, 213, 195));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 80, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 220));

        jPanel24.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1100, 450));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1140, 490));

        getContentPane().add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1210, 590));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerTabForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel225;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel232;
    private javax.swing.JPanel jPanel233;
    private javax.swing.JPanel jPanel234;
    private javax.swing.JPanel jPanel235;
    private javax.swing.JPanel jPanel236;
    private javax.swing.JPanel jPanel237;
    private javax.swing.JPanel jPanel238;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel331;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
