/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lameza;

/**
 *
 * @author Kyla Alvarez
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel20 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel36 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jPanel37 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel38 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jPanel95 = new javax.swing.JPanel();
        jPanel96 = new javax.swing.JPanel();
        jLabel105 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel97 = new javax.swing.JPanel();
        jPanel98 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel107 = new javax.swing.JLabel();
        jPanel99 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel100 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jPanel101 = new javax.swing.JPanel();
        jLabel110 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel102 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel103 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jPanel104 = new javax.swing.JPanel();
        jPanel105 = new javax.swing.JPanel();
        jPanel106 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jComboBox29 = new javax.swing.JComboBox<>();
        jPanel107 = new javax.swing.JPanel();
        jLabel114 = new javax.swing.JLabel();
        jComboBox30 = new javax.swing.JComboBox<>();
        jPanel108 = new javax.swing.JPanel();
        jLabel115 = new javax.swing.JLabel();
        jComboBox31 = new javax.swing.JComboBox<>();
        jPanel109 = new javax.swing.JPanel();
        jLabel116 = new javax.swing.JLabel();
        jComboBox32 = new javax.swing.JComboBox<>();
        jLabel117 = new javax.swing.JLabel();
        jPanel110 = new javax.swing.JPanel();
        jPanel111 = new javax.swing.JPanel();
        jLabel118 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel112 = new javax.swing.JPanel();
        jPanel113 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel120 = new javax.swing.JLabel();
        jPanel114 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel115 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jPanel116 = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel117 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jPanel118 = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jPanel119 = new javax.swing.JPanel();
        jPanel120 = new javax.swing.JPanel();
        jPanel121 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        jComboBox33 = new javax.swing.JComboBox<>();
        jPanel122 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jComboBox34 = new javax.swing.JComboBox<>();
        jPanel123 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jComboBox35 = new javax.swing.JComboBox<>();
        jPanel124 = new javax.swing.JPanel();
        jLabel129 = new javax.swing.JLabel();
        jComboBox36 = new javax.swing.JComboBox<>();
        jLabel130 = new javax.swing.JLabel();
        jPanel125 = new javax.swing.JPanel();
        jPanel126 = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel127 = new javax.swing.JPanel();
        jPanel128 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel133 = new javax.swing.JLabel();
        jPanel129 = new javax.swing.JPanel();
        jLabel134 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel130 = new javax.swing.JPanel();
        jLabel135 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jPanel131 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jPanel132 = new javax.swing.JPanel();
        jLabel137 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jPanel133 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        jPanel134 = new javax.swing.JPanel();
        jPanel135 = new javax.swing.JPanel();
        jPanel136 = new javax.swing.JPanel();
        jLabel139 = new javax.swing.JLabel();
        jComboBox37 = new javax.swing.JComboBox<>();
        jPanel137 = new javax.swing.JPanel();
        jLabel140 = new javax.swing.JLabel();
        jComboBox38 = new javax.swing.JComboBox<>();
        jPanel138 = new javax.swing.JPanel();
        jLabel141 = new javax.swing.JLabel();
        jComboBox39 = new javax.swing.JComboBox<>();
        jPanel139 = new javax.swing.JPanel();
        jLabel142 = new javax.swing.JLabel();
        jComboBox40 = new javax.swing.JComboBox<>();
        jLabel143 = new javax.swing.JLabel();
        jPanel140 = new javax.swing.JPanel();
        jPanel141 = new javax.swing.JPanel();
        jLabel144 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jPanel142 = new javax.swing.JPanel();
        jPanel143 = new javax.swing.JPanel();
        jLabel145 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel146 = new javax.swing.JLabel();
        jPanel144 = new javax.swing.JPanel();
        jLabel147 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel145 = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jPanel146 = new javax.swing.JPanel();
        jLabel149 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jPanel147 = new javax.swing.JPanel();
        jLabel150 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jPanel148 = new javax.swing.JPanel();
        jLabel151 = new javax.swing.JLabel();
        jPanel149 = new javax.swing.JPanel();
        jPanel150 = new javax.swing.JPanel();
        jPanel151 = new javax.swing.JPanel();
        jLabel152 = new javax.swing.JLabel();
        jComboBox41 = new javax.swing.JComboBox<>();
        jPanel152 = new javax.swing.JPanel();
        jLabel153 = new javax.swing.JLabel();
        jComboBox42 = new javax.swing.JComboBox<>();
        jPanel153 = new javax.swing.JPanel();
        jLabel154 = new javax.swing.JLabel();
        jComboBox43 = new javax.swing.JComboBox<>();
        jPanel154 = new javax.swing.JPanel();
        jLabel155 = new javax.swing.JLabel();
        jComboBox44 = new javax.swing.JComboBox<>();
        jLabel156 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(231, 213, 195));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(102, 51, 0));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(231, 213, 195));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("LAMÈZA  ");
        jPanel24.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -80, -1, -1));

        jPanel25.setBackground(new java.awt.Color(102, 51, 0));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(231, 213, 195));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setText("jLabel46");
        jPanel26.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton3.setText("MAIN COURSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 150));
        jPanel25.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel27.setBackground(new java.awt.Color(231, 213, 195));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setText("jLabel46");
        jPanel27.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton2.setText("APPETIZER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 120, -1));

        jPanel25.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 150));

        jPanel28.setBackground(new java.awt.Color(231, 213, 195));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setText("jLabel46");
        jPanel28.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton1.setText("FORTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel28.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        jPanel25.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 150));

        jPanel29.setBackground(new java.awt.Color(231, 213, 195));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setText("jLabel46");
        jPanel29.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton4.setText("DESSERT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel29.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel25.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 150));

        jPanel30.setBackground(new java.awt.Color(231, 213, 195));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setText("jLabel46");
        jPanel30.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton5.setText("BEVERAGES");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel25.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 330, 150));

        jScrollPane2.setViewportView(jPanel25);

        jPanel20.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 750));

        jPanel31.setBackground(new java.awt.Color(102, 51, 0));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(231, 213, 195));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("LAMÈZA  ");
        jPanel31.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel20.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1460, 90));

        jPanel32.setBackground(new java.awt.Color(102, 51, 0));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBackground(new java.awt.Color(231, 213, 195));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBackground(new java.awt.Color(102, 51, 0));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setBackground(new java.awt.Color(231, 213, 195));
        jLabel53.setForeground(new java.awt.Color(231, 213, 195));
        jLabel53.setText("jLabel52");
        jPanel35.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel35.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel33.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 200));

        jPanel36.setBackground(new java.awt.Color(102, 51, 0));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(231, 213, 195));
        jLabel54.setForeground(new java.awt.Color(231, 213, 195));
        jLabel54.setText("jLabel52");
        jPanel36.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel36.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel33.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 200));

        jPanel37.setBackground(new java.awt.Color(102, 51, 0));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setBackground(new java.awt.Color(231, 213, 195));
        jLabel52.setForeground(new java.awt.Color(231, 213, 195));
        jLabel52.setText("jLabel52");
        jPanel37.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel37.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel33.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 430, 200));

        jPanel38.setBackground(new java.awt.Color(102, 51, 0));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(231, 213, 195));
        jLabel55.setForeground(new java.awt.Color(231, 213, 195));
        jLabel55.setText("jLabel52");
        jPanel38.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel38.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel33.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 430, 200));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 460));

        jPanel20.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 960, 500));

        jLabel51.setBackground(new java.awt.Color(102, 51, 0));
        jLabel51.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 51, 0));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("LAMÈZA  forte");
        jPanel20.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 400, 60));

        jTabbedPane1.addTab("Forte", jPanel20);

        jPanel95.setBackground(new java.awt.Color(231, 213, 195));
        jPanel95.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel96.setBackground(new java.awt.Color(102, 51, 0));
        jPanel96.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel105.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(231, 213, 195));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("LAMÈZA  ");
        jPanel96.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel95.add(jPanel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -80, -1, -1));

        jPanel97.setBackground(new java.awt.Color(102, 51, 0));
        jPanel97.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel98.setBackground(new java.awt.Color(231, 213, 195));
        jPanel98.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel106.setText("jLabel46");
        jPanel98.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton7.setText("MAIN COURSE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel98.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel97.add(jPanel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 150));
        jPanel97.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel99.setBackground(new java.awt.Color(231, 213, 195));
        jPanel99.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel108.setText("jLabel46");
        jPanel99.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton8.setText("APPETIZER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel99.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 120, -1));

        jPanel97.add(jPanel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 150));

        jPanel100.setBackground(new java.awt.Color(231, 213, 195));
        jPanel100.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel109.setText("jLabel46");
        jPanel100.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton26.setText("FORTE");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel100.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        jPanel97.add(jPanel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 150));

        jPanel101.setBackground(new java.awt.Color(231, 213, 195));
        jPanel101.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel110.setText("jLabel46");
        jPanel101.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton6.setText("DESSERT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel101.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel97.add(jPanel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 150));

        jPanel102.setBackground(new java.awt.Color(231, 213, 195));
        jPanel102.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel111.setText("jLabel46");
        jPanel102.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton9.setText("BEVERAGES");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel102.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel97.add(jPanel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 330, 150));

        jScrollPane7.setViewportView(jPanel97);

        jPanel95.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 750));

        jPanel103.setBackground(new java.awt.Color(102, 51, 0));
        jPanel103.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(231, 213, 195));
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("LAMÈZA  ");
        jPanel103.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel95.add(jPanel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1460, 90));

        jPanel104.setBackground(new java.awt.Color(102, 51, 0));
        jPanel104.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel105.setBackground(new java.awt.Color(231, 213, 195));
        jPanel105.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel106.setBackground(new java.awt.Color(102, 51, 0));
        jPanel106.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel113.setBackground(new java.awt.Color(231, 213, 195));
        jLabel113.setForeground(new java.awt.Color(231, 213, 195));
        jLabel113.setText("jLabel52");
        jPanel106.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel106.add(jComboBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel105.add(jPanel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 200));

        jPanel107.setBackground(new java.awt.Color(102, 51, 0));
        jPanel107.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel114.setBackground(new java.awt.Color(231, 213, 195));
        jLabel114.setForeground(new java.awt.Color(231, 213, 195));
        jLabel114.setText("jLabel52");
        jPanel107.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel107.add(jComboBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel105.add(jPanel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 200));

        jPanel108.setBackground(new java.awt.Color(102, 51, 0));
        jPanel108.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel115.setBackground(new java.awt.Color(231, 213, 195));
        jLabel115.setForeground(new java.awt.Color(231, 213, 195));
        jLabel115.setText("jLabel52");
        jPanel108.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel108.add(jComboBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel105.add(jPanel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 430, 200));

        jPanel109.setBackground(new java.awt.Color(102, 51, 0));
        jPanel109.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel116.setBackground(new java.awt.Color(231, 213, 195));
        jLabel116.setForeground(new java.awt.Color(231, 213, 195));
        jLabel116.setText("jLabel52");
        jPanel109.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel109.add(jComboBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel105.add(jPanel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 430, 200));

        jPanel104.add(jPanel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 460));

        jPanel95.add(jPanel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 960, 500));

        jLabel117.setBackground(new java.awt.Color(102, 51, 0));
        jLabel117.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel117.setForeground(new java.awt.Color(102, 51, 0));
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("LAMÈZA  appetizer");
        jPanel95.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 540, 60));

        jTabbedPane1.addTab("Appetizer", jPanel95);

        jPanel110.setBackground(new java.awt.Color(231, 213, 195));
        jPanel110.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel111.setBackground(new java.awt.Color(102, 51, 0));
        jPanel111.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel118.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel118.setForeground(new java.awt.Color(231, 213, 195));
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("LAMÈZA  ");
        jPanel111.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel110.add(jPanel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -80, -1, -1));

        jPanel112.setBackground(new java.awt.Color(102, 51, 0));
        jPanel112.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel113.setBackground(new java.awt.Color(231, 213, 195));
        jPanel113.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel119.setText("jLabel46");
        jPanel113.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton12.setText("MAIN COURSE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel113.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel112.add(jPanel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 150));
        jPanel112.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel114.setBackground(new java.awt.Color(231, 213, 195));
        jPanel114.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel121.setText("jLabel46");
        jPanel114.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton10.setText("APPETIZER");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel114.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 120, -1));

        jPanel112.add(jPanel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 150));

        jPanel115.setBackground(new java.awt.Color(231, 213, 195));
        jPanel115.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel122.setText("jLabel46");
        jPanel115.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton27.setText("FORTE");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel115.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        jPanel112.add(jPanel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 150));

        jPanel116.setBackground(new java.awt.Color(231, 213, 195));
        jPanel116.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setText("jLabel46");
        jPanel116.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton13.setText("DESSERT");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel116.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel112.add(jPanel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 150));

        jPanel117.setBackground(new java.awt.Color(231, 213, 195));
        jPanel117.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setText("jLabel46");
        jPanel117.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton28.setText("BEVERAGES");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel117.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel112.add(jPanel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 330, 150));

        jScrollPane8.setViewportView(jPanel112);

        jPanel110.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 750));

        jPanel118.setBackground(new java.awt.Color(102, 51, 0));
        jPanel118.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel125.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel125.setForeground(new java.awt.Color(231, 213, 195));
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel125.setText("LAMÈZA  ");
        jPanel118.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel110.add(jPanel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1460, 90));

        jPanel119.setBackground(new java.awt.Color(102, 51, 0));
        jPanel119.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel120.setBackground(new java.awt.Color(231, 213, 195));
        jPanel120.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel121.setBackground(new java.awt.Color(102, 51, 0));
        jPanel121.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel126.setBackground(new java.awt.Color(231, 213, 195));
        jLabel126.setForeground(new java.awt.Color(231, 213, 195));
        jLabel126.setText("jLabel52");
        jPanel121.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox33.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel121.add(jComboBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel120.add(jPanel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 200));

        jPanel122.setBackground(new java.awt.Color(102, 51, 0));
        jPanel122.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel127.setBackground(new java.awt.Color(231, 213, 195));
        jLabel127.setForeground(new java.awt.Color(231, 213, 195));
        jLabel127.setText("jLabel52");
        jPanel122.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox34.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel122.add(jComboBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel120.add(jPanel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 200));

        jPanel123.setBackground(new java.awt.Color(102, 51, 0));
        jPanel123.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel128.setBackground(new java.awt.Color(231, 213, 195));
        jLabel128.setForeground(new java.awt.Color(231, 213, 195));
        jLabel128.setText("jLabel52");
        jPanel123.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox35.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel123.add(jComboBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel120.add(jPanel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 430, 200));

        jPanel124.setBackground(new java.awt.Color(102, 51, 0));
        jPanel124.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel129.setBackground(new java.awt.Color(231, 213, 195));
        jLabel129.setForeground(new java.awt.Color(231, 213, 195));
        jLabel129.setText("jLabel52");
        jPanel124.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox36.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel124.add(jComboBox36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel120.add(jPanel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 430, 200));

        jPanel119.add(jPanel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 460));

        jPanel110.add(jPanel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 960, 500));

        jLabel130.setBackground(new java.awt.Color(102, 51, 0));
        jLabel130.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel130.setForeground(new java.awt.Color(102, 51, 0));
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel130.setText("main course");
        jPanel110.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 400, 60));

        jTabbedPane1.addTab("Main Course", jPanel110);

        jPanel125.setBackground(new java.awt.Color(231, 213, 195));
        jPanel125.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel126.setBackground(new java.awt.Color(102, 51, 0));
        jPanel126.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel131.setForeground(new java.awt.Color(231, 213, 195));
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel131.setText("LAMÈZA  ");
        jPanel126.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel125.add(jPanel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -80, -1, -1));

        jPanel127.setBackground(new java.awt.Color(102, 51, 0));
        jPanel127.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel128.setBackground(new java.awt.Color(231, 213, 195));
        jPanel128.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel132.setText("jLabel46");
        jPanel128.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton14.setText("MAIN COURSE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel128.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel127.add(jPanel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 150));
        jPanel127.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel129.setBackground(new java.awt.Color(231, 213, 195));
        jPanel129.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel134.setText("jLabel46");
        jPanel129.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton11.setText("APPETIZER");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel129.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 120, -1));

        jPanel127.add(jPanel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 150));

        jPanel130.setBackground(new java.awt.Color(231, 213, 195));
        jPanel130.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel135.setText("jLabel46");
        jPanel130.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton29.setText("FORTE");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel130.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        jPanel127.add(jPanel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 150));

        jPanel131.setBackground(new java.awt.Color(231, 213, 195));
        jPanel131.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel136.setText("jLabel46");
        jPanel131.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton15.setText("DESSERT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel131.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel127.add(jPanel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 150));

        jPanel132.setBackground(new java.awt.Color(231, 213, 195));
        jPanel132.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel137.setText("jLabel46");
        jPanel132.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton30.setText("BEVERAGES");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel132.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel127.add(jPanel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 330, 150));

        jScrollPane9.setViewportView(jPanel127);

        jPanel125.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 750));

        jPanel133.setBackground(new java.awt.Color(102, 51, 0));
        jPanel133.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel138.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(231, 213, 195));
        jLabel138.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel138.setText("LAMÈZA  ");
        jPanel133.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel125.add(jPanel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1460, 90));

        jPanel134.setBackground(new java.awt.Color(102, 51, 0));
        jPanel134.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel135.setBackground(new java.awt.Color(231, 213, 195));
        jPanel135.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel136.setBackground(new java.awt.Color(102, 51, 0));
        jPanel136.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel139.setBackground(new java.awt.Color(231, 213, 195));
        jLabel139.setForeground(new java.awt.Color(231, 213, 195));
        jLabel139.setText("jLabel52");
        jPanel136.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel136.add(jComboBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel135.add(jPanel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 200));

        jPanel137.setBackground(new java.awt.Color(102, 51, 0));
        jPanel137.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel140.setBackground(new java.awt.Color(231, 213, 195));
        jLabel140.setForeground(new java.awt.Color(231, 213, 195));
        jLabel140.setText("jLabel52");
        jPanel137.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox38.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel137.add(jComboBox38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel135.add(jPanel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 200));

        jPanel138.setBackground(new java.awt.Color(102, 51, 0));
        jPanel138.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel141.setBackground(new java.awt.Color(231, 213, 195));
        jLabel141.setForeground(new java.awt.Color(231, 213, 195));
        jLabel141.setText("jLabel52");
        jPanel138.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox39.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel138.add(jComboBox39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel135.add(jPanel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 430, 200));

        jPanel139.setBackground(new java.awt.Color(102, 51, 0));
        jPanel139.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel142.setBackground(new java.awt.Color(231, 213, 195));
        jLabel142.setForeground(new java.awt.Color(231, 213, 195));
        jLabel142.setText("jLabel52");
        jPanel139.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox40.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel139.add(jComboBox40, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel135.add(jPanel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 430, 200));

        jPanel134.add(jPanel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 460));

        jPanel125.add(jPanel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 960, 500));

        jLabel143.setBackground(new java.awt.Color(102, 51, 0));
        jLabel143.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(102, 51, 0));
        jLabel143.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel143.setText("LAMÈZA  dessert");
        jPanel125.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 460, 60));

        jTabbedPane1.addTab("Dessert", jPanel125);

        jPanel140.setBackground(new java.awt.Color(231, 213, 195));
        jPanel140.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel141.setBackground(new java.awt.Color(102, 51, 0));
        jPanel141.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel144.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(231, 213, 195));
        jLabel144.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel144.setText("LAMÈZA  ");
        jPanel141.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel140.add(jPanel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -80, -1, -1));

        jPanel142.setBackground(new java.awt.Color(102, 51, 0));
        jPanel142.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel143.setBackground(new java.awt.Color(231, 213, 195));
        jPanel143.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel145.setText("jLabel46");
        jPanel143.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton17.setText("MAIN COURSE");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel143.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel142.add(jPanel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 330, 150));
        jPanel142.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 910, 50, 20));

        jPanel144.setBackground(new java.awt.Color(231, 213, 195));
        jPanel144.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel147.setText("jLabel46");
        jPanel144.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton16.setText("APPETIZER");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel144.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 120, 120, -1));

        jPanel142.add(jPanel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 150));

        jPanel145.setBackground(new java.awt.Color(231, 213, 195));
        jPanel145.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel148.setText("jLabel46");
        jPanel145.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton31.setText("FORTE");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel145.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));

        jPanel142.add(jPanel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 150));

        jPanel146.setBackground(new java.awt.Color(231, 213, 195));
        jPanel146.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel149.setText("jLabel46");
        jPanel146.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton18.setText("MAIN COURSE");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel146.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel142.add(jPanel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 330, 150));

        jPanel147.setBackground(new java.awt.Color(231, 213, 195));
        jPanel147.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel150.setText("jLabel46");
        jPanel147.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 277, 130));

        jButton32.setText("BEVERAGES");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel147.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 120, -1));

        jPanel142.add(jPanel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 330, 150));

        jScrollPane10.setViewportView(jPanel142);

        jPanel140.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 750));

        jPanel148.setBackground(new java.awt.Color(102, 51, 0));
        jPanel148.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel151.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(231, 213, 195));
        jLabel151.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel151.setText("LAMÈZA  ");
        jPanel148.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel140.add(jPanel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1460, 90));

        jPanel149.setBackground(new java.awt.Color(102, 51, 0));
        jPanel149.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel150.setBackground(new java.awt.Color(231, 213, 195));
        jPanel150.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel151.setBackground(new java.awt.Color(102, 51, 0));
        jPanel151.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel152.setBackground(new java.awt.Color(231, 213, 195));
        jLabel152.setForeground(new java.awt.Color(231, 213, 195));
        jLabel152.setText("jLabel52");
        jPanel151.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox41.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel151.add(jComboBox41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel150.add(jPanel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 200));

        jPanel152.setBackground(new java.awt.Color(102, 51, 0));
        jPanel152.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel153.setBackground(new java.awt.Color(231, 213, 195));
        jLabel153.setForeground(new java.awt.Color(231, 213, 195));
        jLabel153.setText("jLabel52");
        jPanel152.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox42.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel152.add(jComboBox42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel150.add(jPanel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 430, 200));

        jPanel153.setBackground(new java.awt.Color(102, 51, 0));
        jPanel153.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel154.setBackground(new java.awt.Color(231, 213, 195));
        jLabel154.setForeground(new java.awt.Color(231, 213, 195));
        jLabel154.setText("jLabel52");
        jPanel153.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox43.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel153.add(jComboBox43, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel150.add(jPanel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 430, 200));

        jPanel154.setBackground(new java.awt.Color(102, 51, 0));
        jPanel154.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel155.setBackground(new java.awt.Color(231, 213, 195));
        jLabel155.setForeground(new java.awt.Color(231, 213, 195));
        jLabel155.setText("jLabel52");
        jPanel154.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 160));

        jComboBox44.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel154.add(jComboBox44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jPanel150.add(jPanel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 430, 200));

        jPanel149.add(jPanel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 460));

        jPanel140.add(jPanel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 960, 500));

        jLabel156.setBackground(new java.awt.Color(102, 51, 0));
        jLabel156.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(102, 51, 0));
        jLabel156.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel156.setText("LAMÈZA  beverages");
        jPanel140.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 550, 60));

        jTabbedPane1.addTab("Beverage", jPanel140);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);

    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox31;
    private javax.swing.JComboBox<String> jComboBox32;
    private javax.swing.JComboBox<String> jComboBox33;
    private javax.swing.JComboBox<String> jComboBox34;
    private javax.swing.JComboBox<String> jComboBox35;
    private javax.swing.JComboBox<String> jComboBox36;
    private javax.swing.JComboBox<String> jComboBox37;
    private javax.swing.JComboBox<String> jComboBox38;
    private javax.swing.JComboBox<String> jComboBox39;
    private javax.swing.JComboBox<String> jComboBox40;
    private javax.swing.JComboBox<String> jComboBox41;
    private javax.swing.JComboBox<String> jComboBox42;
    private javax.swing.JComboBox<String> jComboBox43;
    private javax.swing.JComboBox<String> jComboBox44;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel111;
    private javax.swing.JPanel jPanel112;
    private javax.swing.JPanel jPanel113;
    private javax.swing.JPanel jPanel114;
    private javax.swing.JPanel jPanel115;
    private javax.swing.JPanel jPanel116;
    private javax.swing.JPanel jPanel117;
    private javax.swing.JPanel jPanel118;
    private javax.swing.JPanel jPanel119;
    private javax.swing.JPanel jPanel120;
    private javax.swing.JPanel jPanel121;
    private javax.swing.JPanel jPanel122;
    private javax.swing.JPanel jPanel123;
    private javax.swing.JPanel jPanel124;
    private javax.swing.JPanel jPanel125;
    private javax.swing.JPanel jPanel126;
    private javax.swing.JPanel jPanel127;
    private javax.swing.JPanel jPanel128;
    private javax.swing.JPanel jPanel129;
    private javax.swing.JPanel jPanel130;
    private javax.swing.JPanel jPanel131;
    private javax.swing.JPanel jPanel132;
    private javax.swing.JPanel jPanel133;
    private javax.swing.JPanel jPanel134;
    private javax.swing.JPanel jPanel135;
    private javax.swing.JPanel jPanel136;
    private javax.swing.JPanel jPanel137;
    private javax.swing.JPanel jPanel138;
    private javax.swing.JPanel jPanel139;
    private javax.swing.JPanel jPanel140;
    private javax.swing.JPanel jPanel141;
    private javax.swing.JPanel jPanel142;
    private javax.swing.JPanel jPanel143;
    private javax.swing.JPanel jPanel144;
    private javax.swing.JPanel jPanel145;
    private javax.swing.JPanel jPanel146;
    private javax.swing.JPanel jPanel147;
    private javax.swing.JPanel jPanel148;
    private javax.swing.JPanel jPanel149;
    private javax.swing.JPanel jPanel150;
    private javax.swing.JPanel jPanel151;
    private javax.swing.JPanel jPanel152;
    private javax.swing.JPanel jPanel153;
    private javax.swing.JPanel jPanel154;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanel98;
    private javax.swing.JPanel jPanel99;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
