/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lameza;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;


    public class Reciept extends javax.swing.JFrame {
    private JTable cartTable;
    private JTextField subTotalField;
    private JTextField taxField;
    private JTextField totalField;
    private JTextField paymentMethodField;
    private JTextField amountField;
    private JTextField changeField;
    // Constructor that accepts parameters
      public Reciept(JTable cartTable, JTextField subTotal, JTextField tax, JTextField total, 
                   JTextField paymentMethod, JTextField amount, JTextField change) {
        this.cartTable = cartTable;            // Store reference to cart table
        this.subTotalField = subTotal;         // Store reference to subtotal field
        this.taxField = tax;                   // Store reference to tax field
        this.totalField = total;               // Store reference to total field
        this.paymentMethodField = paymentMethod; // Store reference to payment method field
        this.amountField = amount;             // Store reference to amount field
        this.changeField = change;             // Store reference to change field

        // Initialize other components and update the receipt display
        initComponents();
        updateReceipt();
    }

    private void updateReceipt() {
    // Get the model from the cart table
    DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

    // Clear the receipt table and populate it with the cart items
    DefaultTableModel receiptTableModel = (DefaultTableModel) jRecieptTable.getModel();
    receiptTableModel.setRowCount(0);  // Clear existing rows

    // Populate receipt table with cart items (Qty, Item, Price)
    for (int row = 0; row < model.getRowCount(); row++) {
        String item = model.getValueAt(row, 0).toString();
        double price = Double.parseDouble(model.getValueAt(row, 1).toString());
        int quantity = Integer.parseInt(model.getValueAt(row, 2).toString());
        double subtotal = price * quantity;
        
        // Add the item to the receipt table
        receiptTableModel.addRow(new Object[]{quantity, item, price, subtotal});
    }

    // Update the subtotal, tax, total, payment method, amount, and change in the receipt
    jRecieptSubTotal.setText(this.subTotalField.getText());
    jRecieptTax.setText(this.taxField.getText());
    jReceiptTotal.setText(this.totalField.getText());
    jRecieptAmountPayment.setText(this.paymentMethodField.getText());
    jRecieptAmountPayment1.setText(this.amountField.getText());
    jRecieptAmountPayment.setText(this.changeField.getText());
}
    


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel319 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRecieptTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jReceiptTotal = new javax.swing.JTextField();
        jRecieptSubTotal = new javax.swing.JTextField();
        jRecieptTax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRecieptAmountPayment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRecieptAmountPayment1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 5, true));
        jPanel1.setForeground(new java.awt.Color(102, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel319.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel319.setForeground(new java.awt.Color(102, 51, 0));
        jLabel319.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel319.setText("LAMÈZA  ");
        jPanel1.add(jLabel319, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 220, -1));

        jRecieptTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRecieptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Qty", "Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(jRecieptTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, 290));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("THANK YOU FOR ORDERING!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));
        jPanel1.add(jReceiptTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 80, 30));

        jRecieptSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecieptSubTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jRecieptSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 80, 30));
        jPanel1.add(jRecieptTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Total:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Payment Method:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Tax (10%):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, 30));

        jCheckBox2.setText("Bank Trasfer");
        jCheckBox2.setContentAreaFilled(false);
        jCheckBox2.setFocusPainted(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jCheckBox3.setText("Cash");
        jCheckBox3.setContentAreaFilled(false);
        jCheckBox3.setFocusPainted(false);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jCheckBox4.setText("E-Wallet");
        jCheckBox4.setContentAreaFilled(false);
        jCheckBox4.setFocusPainted(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jCheckBox5.setText("Debit or Credit Card");
        jCheckBox5.setContentAreaFilled(false);
        jCheckBox5.setFocusPainted(false);
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Change:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("ORDER RECEIPT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jRecieptAmountPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecieptAmountPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jRecieptAmountPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 80, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("SubTotal:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 30));

        jRecieptAmountPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecieptAmountPayment1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRecieptAmountPayment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 80, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("Payment:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 419, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jRecieptSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecieptSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRecieptSubTotalActionPerformed

    private void jRecieptAmountPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecieptAmountPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRecieptAmountPaymentActionPerformed

    private void jRecieptAmountPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecieptAmountPayment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRecieptAmountPayment1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

   

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // We already created the instance in the code above, so no need to call new Reciept() here.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel319;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jReceiptTotal;
    private javax.swing.JTextField jRecieptAmountPayment;
    private javax.swing.JTextField jRecieptAmountPayment1;
    private javax.swing.JTextField jRecieptSubTotal;
    private javax.swing.JTable jRecieptTable;
    private javax.swing.JTextField jRecieptTax;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
