package Lameza;

import Controller_Connector.DBConnect;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class ReservationRequestForm extends javax.swing.JFrame {

    // This will hold the reserved tables in memory
    private java.util.Set<String> reservedTables;
    private Connection con;

    /**
     * Creates new form ReservationRequestForm
     */
    public ReservationRequestForm() {
        initComponents();
        // Get the database connection using DBConnect class
        DBConnect dbc = new DBConnect();
        con = dbc.getConnection(); // DBConnect already returns a Connection object
        // Initialize the reservedTables set
        reservedTables = new java.util.HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(231, 213, 195));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 1350, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(231, 213, 195));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LAMÈZA  ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1470, 90));

        jLabel21.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(" LAMÈZA ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, 330, 60));

        jPanel3.setBackground(new java.awt.Color(102, 51, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, 30));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 250, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 250, 30));

        jComboBox2.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034" }));
        jComboBox2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 90, 30));

        jComboBox1.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 213, 195));
        jLabel2.setText("NAME:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 213, 195));
        jLabel3.setText("CONTACT NUMBER:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 213, 195));
        jLabel4.setText("EMAIL:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(231, 213, 195));
        jLabel7.setText("CHOOSE TABLE:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 213, 195));
        jLabel6.setText("DATE OF RESERVATION:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 213, 195));
        jLabel5.setText("NUMBER OF SEATS:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel22.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(231, 213, 195));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("reservation request");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(231, 213, 195));
        jLabel11.setText("TIME OF RESERVATION:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox4.setForeground(new java.awt.Color(102, 51, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TABLE 1", "TABLE 2", "TABLE 3", "TABLE 4", "TABLE 5", "TABLE 6", "TABLE 7", "TABLE 8", " " }));
        jComboBox4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 170, 30));

        jButton1.setBackground(new java.awt.Color(231, 213, 195));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 0));
        jButton1.setText("CONFIRM RESERVATION");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 230, 30));

        jComboBox5.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jComboBox5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 70, 30));

        jComboBox6.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", " " }));
        jComboBox6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 70, 30));

        jComboBox7.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        jComboBox7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 90, 30));

        jComboBox8.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jComboBox8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 30));

        jComboBox3.setBackground(new java.awt.Color(231, 213, 195));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 250, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 490, 510));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/homepage (2).jpg"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1470, 550));

        jPanel4.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 630, 10));

        jPanel6.setBackground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 600, -1));

        jPanel8.setBackground(new java.awt.Color(102, 51, 0));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(231, 213, 195));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/royale (1).jpg"))); // NOI18N
        jLabel27.setText("TABLE 3");
        jLabel27.setOpaque(true);
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 290, 180));

        jPanel9.setBackground(new java.awt.Color(102, 51, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(204, 204, 255));
        jLabel29.setText("TABLE 1");
        jLabel29.setOpaque(true);
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 290, 180));

        jLabel30.setBackground(new java.awt.Color(0, 204, 204));
        jLabel30.setText("TABLE 4");
        jLabel30.setOpaque(true);
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 290, 180));

        jLabel31.setBackground(new java.awt.Color(255, 51, 102));
        jLabel31.setText("TABLE 3");
        jLabel31.setOpaque(true);
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 290, 180));

        jLabel32.setBackground(new java.awt.Color(255, 102, 153));
        jLabel32.setText("TABLE 5");
        jLabel32.setOpaque(true);
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 180));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 1460, 260));

        jPanel11.setBackground(new java.awt.Color(231, 213, 195));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(231, 213, 195));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/amour (2).jpg"))); // NOI18N
        jLabel28.setOpaque(true);
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 310, 200));

        jLabel34.setBackground(new java.awt.Color(231, 213, 195));
        jLabel34.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(231, 213, 195));
        jLabel34.setText("Lamèza Serene ");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, -1, -1));

        jPanel15.setBackground(new java.awt.Color(231, 213, 195));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(231, 213, 195));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/harmonie.jpg"))); // NOI18N
        jLabel13.setText("TABLE 4");
        jLabel13.setOpaque(true);
        jPanel15.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

        jPanel8.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 310, 200));

        jPanel14.setBackground(new java.awt.Color(231, 213, 195));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(231, 213, 195));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/serene (1).jpg"))); // NOI18N
        jLabel25.setText("TABLE 1");
        jLabel25.setOpaque(true);
        jPanel14.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 310, 200));

        jPanel16.setBackground(new java.awt.Color(231, 213, 195));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel36.setBackground(new java.awt.Color(231, 213, 195));
        jLabel36.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(231, 213, 195));
        jLabel36.setText("Lamèza Royale ");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel37.setBackground(new java.awt.Color(231, 213, 195));
        jLabel37.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(231, 213, 195));
        jLabel37.setText("Lamèza Harmonie ");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        jLabel38.setBackground(new java.awt.Color(231, 213, 195));
        jLabel38.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(231, 213, 195));
        jLabel38.setText("Lamèza Amour ");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 1460, 270));

        jPanel5.setBackground(new java.awt.Color(102, 51, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 51, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("TABLE 1");
        jLabel10.setOpaque(true);
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, 290, 180));

        jLabel18.setBackground(new java.awt.Color(0, 204, 204));
        jLabel18.setText("TABLE 4");
        jLabel18.setOpaque(true);
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 290, 180));

        jLabel19.setBackground(new java.awt.Color(255, 51, 102));
        jLabel19.setText("TABLE 3");
        jLabel19.setOpaque(true);
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 290, 180));

        jLabel24.setBackground(new java.awt.Color(255, 102, 153));
        jLabel24.setText("TABLE 5");
        jLabel24.setOpaque(true);
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 290, 180));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 1460, 260));

        jLabel26.setBackground(new java.awt.Color(231, 213, 195));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/soleill.jpg"))); // NOI18N
        jLabel26.setText("TABLE 4");
        jLabel26.setOpaque(true);
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 290, 180));

        jPanel12.setBackground(new java.awt.Color(231, 213, 195));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(231, 213, 195));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/velours.jpg"))); // NOI18N
        jLabel14.setText("TABLE 5");
        jLabel14.setOpaque(true);
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 310, 200));

        jLabel35.setBackground(new java.awt.Color(231, 213, 195));
        jLabel35.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(231, 213, 195));
        jLabel35.setText("Lamèza Luxe");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, -1, -1));

        jPanel13.setBackground(new java.awt.Color(231, 213, 195));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(231, 213, 195));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/verre.jpg"))); // NOI18N
        jLabel12.setText("TABLE 3");
        jLabel12.setOpaque(true);
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

        jPanel5.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 310, 200));

        jLabel39.setBackground(new java.awt.Color(231, 213, 195));
        jLabel39.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(231, 213, 195));
        jLabel39.setText("Lamèza Velour");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jPanel17.setBackground(new java.awt.Color(231, 213, 195));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 310, 200));

        jPanel18.setBackground(new java.awt.Color(231, 213, 195));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(231, 213, 195));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/luxe.jpg"))); // NOI18N
        jLabel8.setText("TABLE 1");
        jLabel8.setOpaque(true);
        jPanel18.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 180));

        jPanel5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, 310, 200));

        jLabel40.setBackground(new java.awt.Color(231, 213, 195));
        jLabel40.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(231, 213, 195));
        jLabel40.setText("Lamèza Verre");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel41.setBackground(new java.awt.Color(231, 213, 195));
        jLabel41.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(231, 213, 195));
        jLabel41.setText("Lamèza Soleil");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1060, 1460, 270));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = jTextField1.getText();
        String contactNumber = jTextField2.getText();
        String email = jTextField3.getText();
        String numberOfSeats = (String) jComboBox3.getSelectedItem();
        String hour = (String) jComboBox5.getSelectedItem();
        String minute = (String) jComboBox6.getSelectedItem();
        String ampm = (String) jComboBox7.getSelectedItem();
        String month = (String) jComboBox1.getSelectedItem();
        String day = (String) jComboBox8.getSelectedItem();
        String year = (String) jComboBox2.getSelectedItem();
        String table = (String) jComboBox4.getSelectedItem(); // Selected table

        // Combine hour, minute, and AM/PM for time
        String time = hour + ":" + minute + " " + ampm;
        String date = year + "-" + month + "-" + day;  // SQL-friendly date format (YYYY-MM-DD)

        // Validate inputs (check for missing data)
        if (name.isEmpty() || contactNumber.isEmpty() || email.isEmpty() || date.isEmpty() || table.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Please fill out all fields before submitting.",
                "Missing Information",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Check if the selected table is already reserved
        if (reservedTables.contains(table)) {
            JOptionPane.showMessageDialog(
                this,
                "Table " + table + " is already reserved. Please choose another table.",
                "Table Already Reserved",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Add the selected table to the reserved set to mark it as reserved
        reservedTables.add(table);

        // Insert the reservation data into the database
        try {
            // Prepare the SQL query to insert reservation data
            Statement state = con.createStatement();
            String query = String.format(
                "INSERT INTO `reservation` (`ReservationID`, `Name`, `Email`, `Num_of_Seats`, `Date_of_Reservation`, `Time_of_Reservation`, `Table`) " +
                "VALUES (NULL, '%s', '%s', '%s', '%s', '%s', '%s')",
                name, email, numberOfSeats, date, time, table
            );

            // Execute the query
            int result = state.executeUpdate(query);

            // Check if the query was successful
            if (result > 0) {
                // If successful, display confirmation
                String confirmationMessage = String.format(
                    "Reservation Submitted Successfully!\n\nDetails:\n" +
                    "Name: %s\nContact Number: %s\nEmail: %s\nNumber of Seats: %s\n" +
                    "Date of Reservation: %s\nTime of Reservation: %s\nTable: %s",
                    name, contactNumber, email, numberOfSeats, date, time, table
                );
                JOptionPane.showMessageDialog(this, confirmationMessage, "Reservation Confirmation", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // If insertion failed
                JOptionPane.showMessageDialog(this, "Failed to submit reservation. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            // Handle errors with database insertion
            JOptionPane.showMessageDialog(this, "Error while submitting reservation: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        DBConnect dbc = new DBConnect(); // Assuming DBConnect handles your DB connection
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationRequestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationRequestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
